name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    name: Forge Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.CORE_NEXT_GITHUB_TOKEN }}
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run tests
        run: forge test -vvv
        env:
          FOUNDRY_PROFILE: ci
